# Estacionariedad en covarianza

# (a)

El modelo GARCH(1,1) está dado por:

$$
r_t = \mu + \varepsilon_t
$$

$$
\varepsilon_t = \sigma_t z_t
$$

$$
\sigma_t^2 = \omega + \alpha \varepsilon_{t-1}^2 + \beta \sigma_{t-1}^2
$$

con $\omega>0$, $\alpha \geq 0$ y $\beta \geq 0$.

Como:

$$
\varepsilon_t^2 = \sigma_t^2 z_t^2
$$

podemos definir:

$$
v_t = \varepsilon_t^2 - \sigma_t^2
$$

Entonces:

$$
\varepsilon_t^2 = \sigma_t^2 + v_t
$$

Reemplazando en el modelo GARCH:

$$
\varepsilon_t^2
=
\omega
+
(\alpha+\beta)\varepsilon_{t-1}^2
+
v_t
-
\beta v_{t-1}
$$

Esta expresión tiene forma de un proceso ARMA(1,1) para $\varepsilon_t^2$.

Para que este proceso sea débilmente estacionario, se requiere que:

$$
\boxed{\alpha+\beta<1}
$$

# (b)



Bajo estacionariedad, se cumple que:

$$
E[\sigma_t^2] = E[\varepsilon_t^2] = \sigma^2
$$

Tomamos esperanza en la ecuación:

$$
\sigma_t^2
=
\omega
+
\alpha \varepsilon_{t-1}^2
+
\beta \sigma_{t-1}^2
$$

Entonces:

$$
\sigma^2
=
\omega
+
\alpha \sigma^2
+
\beta \sigma^2
$$

Factorizando:

$$
\sigma^2(1-\alpha-\beta)=\omega
$$

Por lo tanto, la varianza incondicional es:

$$
\boxed{
\sigma^2 = \frac{\omega}{1-\alpha-\beta}
}
$$

# (c)

Cuando:

$$
\alpha+\beta \rightarrow 1
$$

el denominador de la varianza incondicional tiende a cero:

$$
\sigma^2 = \frac{\omega}{1-\alpha-\beta}
$$

Por lo tanto, la varianza incondicional tiende a infinito.

Esto significa que la volatilidad se vuelve extremadamente persistente, es decir, un shock de volatilidad tarda mucho tiempo en desaparecer.

Cuando:

$$
\alpha+\beta=1
$$

el modelo recibe el nombre de **IGARCH**. En este caso, los shocks de volatilidad tienen efectos muy duraderos y la varianza incondicional no está bien definida.

# Persistencia y Vida Media de un Shock

# (a)

La persistencia de un shock de volatilidad está determinada por la suma:

$$
\alpha+\beta
$$

La desviación de la volatilidad respecto de su media se transmite en el tiempo según:

$$
E[\sigma_{t+h}^2-\sigma^2 \mid \mathcal{F}_t]
=
(\alpha+\beta)^h
(\sigma_{t+1}^2-\sigma^2)
$$

Esto muestra que el impacto del shock disminuye geométricamente a tasa $\alpha+\beta$.

Por lo tanto:

$$
\boxed{\alpha+\beta}
$$

# (b)

La vida media, o *half-life*, corresponde al número de períodos necesarios para que el efecto de un shock se reduzca a la mitad.

Entonces:

$$
(\alpha+\beta)^{h^*}=0.5
$$

Aplicando logaritmos:

$$
h^* \ln(\alpha+\beta)=\ln(0.5)
$$

Despejando:

$$
\boxed{
h^*=\frac{\ln(0.5)}{\ln(\alpha+\beta)}
}
$$

In [1]:
import numpy as np
import pandas as pd

parametros = [
    (0.05, 0.90),
    (0.10, 0.85),
    (0.02, 0.97)
]

resultados = []

for alpha, beta in parametros:
    persistencia = alpha + beta
    vida_media = np.log(0.5) / np.log(persistencia)
    
    resultados.append({
        "alpha": alpha,
        "beta": beta,
        "alpha + beta": persistencia,
        "vida media": vida_media
    })

tabla_vida_media = pd.DataFrame(resultados)
tabla_vida_media

   alpha  beta  alpha + beta  vida media
0   0.05  0.90          0.95   13.513407
1   0.10  0.85          0.95   13.513407
2   0.02  0.97          0.99   68.967564

# (c)

Los dos primeros casos tienen la misma persistencia:

$$
\alpha+\beta = 0.95
$$

Por eso ambos tienen la misma vida media, cercana a 13,5 períodos.

El tercer caso tiene:

$$
\alpha+\beta = 0.99
$$

Por lo tanto, su vida media es mucho mayor, cercana a 69 períodos.

La combinación más persistente es:

$$
\boxed{(\alpha,\beta)=(0.02,0.97)}
$$

Esto ocurre porque tiene el mayor valor de $\alpha+\beta$, lo que implica que los shocks de volatilidad desaparecen más lentamente.

# Momento de Cuarto Orden y Curtosis

# (a)

La curtosis incondicional de $\varepsilon_t$ en un modelo GARCH(1,1) con innovaciones normales está dada por:

$$
\kappa
=
\frac{
3[1-(\alpha+\beta)^2]
}{
1-(\alpha+\beta)^2-2\alpha^2
}
$$

Esta expresión muestra que la curtosis depende de los parámetros $\alpha$ y $\beta$ del modelo.

Aunque $z_t$ siga una distribución normal, la variable $\varepsilon_t$ puede presentar una curtosis mayor que 3 debido a la volatilidad condicional cambiante.

# (b)

$$
\kappa > 3
$$

La curtosis es:

$$
\kappa
=
\frac{
3[1-(\alpha+\beta)^2]
}{
1-(\alpha+\beta)^2-2\alpha^2
}
$$

Como $\alpha>0$, se cumple que:

$$
2\alpha^2>0
$$

Por lo tanto:

$$
1-(\alpha+\beta)^2-2\alpha^2
<
1-(\alpha+\beta)^2
$$

Esto significa que el denominador es menor que el numerador interno, por eso:

$$
\kappa>3
$$

En conclusión, el modelo GARCH(1,1) con innovaciones normales genera exceso de curtosis incondicional, es decir, aunque los shocks $z_t$ sean normales, el modelo puede generar colas más pesadas y más eventos extremos, algo típico en series financieras.

In [2]:
resultados = []

for alpha, beta in parametros:
    condicion = 3*alpha**2 + 2*alpha*beta + beta**2
    
    if condicion < 1:
        curtosis = 3*(1-(alpha+beta)**2) / (1-(alpha+beta)**2 - 2*alpha**2)
    else:
        curtosis = np.nan
    
    resultados.append({
        "alpha": alpha,
        "beta": beta,
        "condición": condicion,
        "existe cuarto momento": condicion < 1,
        "curtosis": curtosis
    })

tabla_curtosis = pd.DataFrame(resultados)
tabla_curtosis

   alpha  beta  condición  existe cuarto momento  curtosis
0   0.05  0.90     0.9075                   True  3.162162
1   0.10  0.85     0.9225                   True  3.774194
2   0.02  0.97     0.9809                   True  3.125654

# (c)

La condición para que exista el cuarto momento incondicional es:

$$
3\alpha^2+2\alpha\beta+\beta^2<1
$$

A partir de los resultados obtenidos, los tres pares de parámetros cumplen esta condición.

Por lo tanto, en los tres casos existe el cuarto momento incondicional y la curtosis está definida.

Además, en todos los casos la curtosis es mayor que 3, lo que confirma que el modelo GARCH(1,1) genera exceso de curtosis respecto de una distribución normal.